;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Input.BlockInput.UI",NewTagName="Input.BlockInput.InventoryOpen")
+GameplayTagRedirects=(OldTagName="Equipment.Slot.Bolls",NewTagName="Equipment.Slot.Bolts")
+GameplayTagList=(Tag="Ability.Context.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Character.Enemy.Primary",DevComment="")
+GameplayTagList=(Tag="Character.Player.Default",DevComment="")
+GameplayTagList=(Tag="Combat.DamageType.Fire",DevComment="")
+GameplayTagList=(Tag="Combat.DamageType.Ice",DevComment="")
+GameplayTagList=(Tag="Combat.Event.HitEnd",DevComment="")
+GameplayTagList=(Tag="Combat.Event.HitStart",DevComment="")
+GameplayTagList=(Tag="Combat.Event.Kick",DevComment="")
+GameplayTagList=(Tag="Combat.Event.State.HitReact",DevComment="")
+GameplayTagList=(Tag="Combat.Event.SwordComboEnd",DevComment="")
+GameplayTagList=(Tag="Combat.Event.SwordComboStart",DevComment="")
+GameplayTagList=(Tag="Combat.Immunity.FireDamage",DevComment="")
+GameplayTagList=(Tag="Door.Closed",DevComment="")
+GameplayTagList=(Tag="Door.Closing",DevComment="")
+GameplayTagList=(Tag="Door.Open",DevComment="")
+GameplayTagList=(Tag="Door.Opening",DevComment="")
+GameplayTagList=(Tag="Equipment.Ability.Assasination",DevComment="")
+GameplayTagList=(Tag="Equipment.Ability.DynamicProjectile.Type1",DevComment="")
+GameplayTagList=(Tag="Equipment.Ability.DynamicProjectile.Type2",DevComment="")
+GameplayTagList=(Tag="Equipment.Ability.SwordAttack",DevComment="")
+GameplayTagList=(Tag="Equipment.AttachPoint.Back",DevComment="")
+GameplayTagList=(Tag="Equipment.AttachPoint.LeftHand",DevComment="")
+GameplayTagList=(Tag="Equipment.AttachPoint.RightHand",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Bolts",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Bombs",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Boots",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Chest",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Consumable",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Gauntlets",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.RangedWeapon",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.SilverWeapon",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.SteelWeapon",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Trousers",DevComment="")
+GameplayTagList=(Tag="Equipment.Slot.Utility",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Player.LevelUp",DevComment="")
+GameplayTagList=(Tag="Input.AssasinationAbility",DevComment="")
+GameplayTagList=(Tag="Input.AttackAbility",DevComment="")
+GameplayTagList=(Tag="Input.BlockInput.InventoryOpen",DevComment="")
+GameplayTagList=(Tag="Input.DynamicProjectileAbility",DevComment="")
+GameplayTagList=(Tag="Input.EAbility",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.DropItem",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.EquipItem",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.Exit",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.Open",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.SortItems",DevComment="")
+GameplayTagList=(Tag="Input.Inventory.SortItemsQuickly",DevComment="")
+GameplayTagList=(Tag="Input.QAbility",DevComment="")
+GameplayTagList=(Tag="Input.ShiftAbility",DevComment="")
+GameplayTagList=(Tag="Input.SprintAbility",DevComment="")
+GameplayTagList=(Tag="Item.Consumable",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Bombs",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Bombs.DancingStar",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Bombs.DevilPuffball",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Oils",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Oils.CursedOil",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Oils.NecrophagueOil",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potions",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potions.Alghouldecoction",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potions.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potions.ManaPotion",DevComment="")
+GameplayTagList=(Tag="Item.Consumable.Potions.TawnyOwlUp",DevComment="")
+GameplayTagList=(Tag="Item.Equipment",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Boots.Cavalry",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Chest.BountyHuntersGambeson",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Gauntlets.Feline",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Armor.Trousers.SkelligeCasual",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Utility",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Utility.Torch",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons.Ammunition.Bolts",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons.CommonCrossbow",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons.DwarvenAxe",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons.HeavyMace",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Weapons.RoseOfShaerrawed",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Common",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Magic",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Master",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Relic",DevComment="")
+GameplayTagList=(Tag="Item.Rarity.Witcher",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Boots",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Chest",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Gauntlets",DevComment="")
+GameplayTagList=(Tag="Item.Type.Armor.Trousers",DevComment="")
+GameplayTagList=(Tag="Item.Type.Utility.Torch",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapons.Axe",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapons.Bolts",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapons.Crossbow",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapons.Mace",DevComment="")
+GameplayTagList=(Tag="Item.Type.Weapons.Sword",DevComment="")
+GameplayTagList=(Tag="Keycard.Destroy",DevComment="")
+GameplayTagList=(Tag="Keycard.LevelOne",DevComment="")
+GameplayTagList=(Tag="Keycard.LevelTwo",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Consumable.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Consumable.ManaPotion",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Equipment.LeftHand.Shield.WoodenShield",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Equipment.LeftHand.Weapon.SmallKnife",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Equipment.RightHand.Mace.BrokenMace",DevComment="")
+GameplayTagList=(Tag="Loot.100Chance.Equipment.RightHand.Sword.BronzeSword",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Consumable.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Consumable.ManaPotion",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Equipment.LeftHand.Shield.WoodenShield",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Equipment.LeftHand.Weapon.SmallKnife",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Equipment.RightHand.Mace.BrokenMace",DevComment="")
+GameplayTagList=(Tag="Loot.LowChance.Equipment.RightHand.Sword.BronzeSword",DevComment="")
+GameplayTagList=(Tag="NPC.Option.Crafting",DevComment="")
+GameplayTagList=(Tag="Player.State.Sprint",DevComment="")
+GameplayTagList=(Tag="Projectile.Basic.Type1",DevComment="")
+GameplayTagList=(Tag="Projectile.Basic.Type2",DevComment="")
+GameplayTagList=(Tag="StatEffect.Ability.LowTier.FireBall",DevComment="")
+GameplayTagList=(Tag="StatEffect.Ability.LowTier.IceShards",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.HighTier.CritChanceUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.HighTier.HealthUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.HighTier.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.HighTier.ShieldUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.CritChanceUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.DamageTypes.FlatFireBaseDamage",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.DamageTypes.FlatIceBaseDamage",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.DamageTypes.Global.CrouchMultiplier",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.DamageTypes.MultiplyFireRangedDamage",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.HealthUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.LowTier.ShieldUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.MidTier",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.MidTier.CritChanceUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.MidTier.HealthUp",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.MidTier.MovementSpeed",DevComment="")
+GameplayTagList=(Tag="StatEffect.Attribute.MidTier.ShieldUp",DevComment="")

